# Generated by Django 5.0.6 on 2024-06-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='destination',
        ),
        migrations.AddField(
            model_name='box',
            name='destination_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
    ]
