# Generated by Django 5.0.6 on 2024-06-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_box_destination_box_destination_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='destination_id',
            field=models.IntegerField(),
        ),
    ]
